### ISSUE TITLE
streaming api does not return

### ISSUE THREAD

**Issue by bhanuvrat** [inueni/birdy#16]
Call to streaming api gets stuck and doesn't ever return. While others work.

    from birdy.twitter import UserClient
    
    CONSUMER_KEY = 'xxxx'
    CONSUMER_SECRET = 'xxxx'
    ACCESS_TOKEN = 'xxxxxxx'
    ACCESS_TOKEN_SECRET = 'xxxx'
    
    client = UserClient(CONSUMER_KEY, CONSUMER_SECRET, ACCESS_TOKEN, ACCESS_TOKEN_SECRET)
    response = client.stream.statuses.filter.post(track='python')
    
    print "doesn't reach here"
    
    for data in response.stream():
        print data

**Comment by sect2k** [comment]
For consuming the streaming API, you need to use `StreamClient` and not `UserClient`. It should work then.

**Comment by bhanuvrat** [comment]
Oh I see ... thanks.

In usage section https://github.com/inueni/birdy#usage streaming apis is used but a streaming client is not created. Hence the confusion.
