### ISSUE TITLE
Add supported Python version to README and setupy.py

### ISSUE THREAD

**Issue by pawelad** [inueni/birdy#26]
Does birdy support Python 3? I looked through README and `setup.py` and couldn't find any answer, other then `Next release (0.3) will focus on Python 3 support` which created more questions (what release is this? it's not in GitHub releases, let's go to PyPI, etc.)

No matter the answer though (which I still don't 100% know ; ), it should be stated somewhere, ideally both in README and in `setupy.py` classifiers.

**Comment by sect2k** [comment]
Resolved in 0.3
