### ISSUE TITLE
Tweets are being truncated at 140 chars

### ISSUE THREAD

**Issue by bathan** [inueni/birdy#32]
The tweets I get when using the SEARCH api are being "truncated" to 140 chars. 

https://developer.twitter.com/en/docs/tweets/tweet-updates

**Comment by sect2k** [comment]
The only thing `birdy` does with returned data is convert it from `json` to native python data types, nothing is being "truncated".

Don't think this is a `birdy` issue.

**Comment by bathan** [comment]
@sect2k thanks for the answer. I'm trying to be able to retrieve tweets using extended mode from twitter , I tried sending the 'tweet_mode': 'extended' into the `client.api.search.tweets.get` params but with no luck. Do you have any example you could provide for allowing tweets to be returned with the extended mode? 

Tweeter docs say : 
```
Consumption
Any REST API endpoints that return Tweets will accept a new tweet_mode request parameter.

Valid request values are compat and extended, which give compatibility mode and extended mode, respectively.

The default mode (if no parameter is provided) is compatibility mode, to support older clients and display methods.

Tweets rendered in compatibility mode via the standard REST API will not contain the extended_tweet field. REST API clients that wish to get the full text can instead opt into extended mode.
```

So I'm just trying to get the full length tweets using your amazing lib but not being able to.
Any idea?

**Comment by bathan** [comment]
Ok, just to help if someone else comes this way. Sending the 'tweet_mode': 'extended' into the client.api.search.tweets.get params actually did the trick. The difference is that instead of the `text` property Tweeter now returns a `full_text` property instead.

**Comment by sect2k** [comment]
Glad to hear you were able to resolve this.
