### ISSUE TITLE
Public stream does not respond with any data

### ISSUE THREAD

**Issue by DJay921** [inueni/birdy#33]
I'm trying a simple example for streaming API but I don't see anything but a blank screen and no output. 
client = UserClient(CONSUMER_KEY,
                    CONSUMER_SECRET,
                    ACCESS_TOKEN,
                    ACCESS_TOKEN_SECRET)

response = client.stream.statuses.filter.post(track='love')

for data in response.stream():
    print(data)

**Comment by sect2k** [comment]
@DipanshuJuneja for streaming API, you need to use `StreamClient` not `UserClient`.
