### ISSUE TITLE
__repr__ override in JSONObject makes JSONObject non-dictlike

### ISSUE THREAD

**Issue by scott2b** [inueni/birdy#7]
JSONObject is not handled correctly by things like the pretty printer because of the __repr__ override. This override seems unnecessary to me.

My general preference would be not to use JSONObject at all, but just to keep things simple by having the response handler return plain dictionaries. Barring that, it would be nice if the JSONObject was pretty printable by not overriding the __repr__.

**Comment by espeed** [comment]
+1 Get rid of JSONObject 

Easy stopgap workaround:

import birdy.twitter
birdy.twitter.JSONObject = dict

**Comment by sect2k** [comment]
Removed __repr__ override in ver 0.3
