### ISSUE TITLE
JSONObject.__getattr__ doesn't work on Python 3.x

### ISSUE THREAD

**Issue by kr41** [inueni/birdy#8]
There is no `iterkeys` method of `dict` objects on Python 3.x, so `__getattr__` falls into infinite recursion:

    File ".../python3.4/site-packages/birdy/twitter.py", line 117, in __getattr__
        if name in self.iterkeys():
    RuntimeError: maximum recursion depth exceeded while calling a Python object

Yes, I see in the docs that Python 3.x is not officially supported. However, the library seems to work on it, and I hope this report will help you to add support of it.

**Comment by scott2b** [comment]
This update does not seem to be available in the pypi release which was updated in Jan 2014. Do you have plans for a new release? Thanks.
